import { type } from "arktype";
import { readDropValidatedBody, throwingArktype } from "~/server/arktype";
import { defineClientEventHandler } from "~/server/internal/clients/event-handler";
import prisma from "~/server/internal/db/database";
import {
  MAX_SECONDS_PER_DAY,
  clampSessionDuration,
  recomputeUserGamePlaytime,
  secondsCreditedInDayBefore,
  capSpans,
  freeSpans,
} from "~/server/internal/playtime/rollup";

const RecordBody = type({
  /** Generated by the client, so a replayed record cannot count twice. */
  sessionId: "string.uuid",
  gameId: "string",
  /** ISO 8601, the client's clock when the game started. */
  startedAt: "string",
  clientDurationSecs: "number >= 0",
}).configure(throwingArktype);

/** Clock skew tolerated on a client-reported start time. */
const MAX_FUTURE_SKEW_MS = 5 * 60 * 1000;
/** Older than this and the record is refused rather than back-dated. */
const MAX_RECORD_AGE_MS = 30 * 24 * 60 * 60 * 1000;

/**
 * POST /api/v1/client/playtime/record
 *
 * Record a whole, already-finished play session in one call.
 *
 * For a launch whose `playtime/start` never reached the server (offline,
 * server down, a slow start the game outran). There is no session to stop, so
 * the client sends what it measured instead of losing the time. The id is
 * client-generated: replaying the same record finds the row it already made
 * and changes nothing, so a lost response can be retried safely.
 *
 * Same clamps as `stop`: at most 48 hours, and never longer than the time
 * since `startedAt`. Because the client chooses `startedAt`, two more limits
 * stop it inventing play, without throwing away time that really happened:
 *   - Time the same user certainly spent in another session is cut out of
 *     the record, which is kept in as many pieces as that leaves. A closed
 *     session counts to its end; an open one only to its last heartbeat. Open
 *     sessions of this game that started inside the span and never
 *     heartbeated are this very play, whose start reached the server too
 *     late for the client to use: they are closed at zero length.
 *   - At most 24 hours are credited in the 24 hours before the record's end;
 *     the record is cut to what is left.
 * When nothing is left: 409 "No playtime left to credit for that day." (the
 * client drops it) or 409 "Session is covered by other play." (the client
 * keeps it and tries again, since a queued stop may still shorten what is in
 * the way).
 */
export default defineClientEventHandler(async (h3, { fetchUser }) => {
  const body = await readDropValidatedBody(h3, RecordBody);
  const user = await fetchUser();

  const now = new Date();
  const startedAt = new Date(body.startedAt);
  if (Number.isNaN(startedAt.getTime()))
    throw createError({ statusCode: 400, statusMessage: "Invalid startedAt." });
  if (startedAt.getTime() > now.getTime() + MAX_FUTURE_SKEW_MS)
    throw createError({
      statusCode: 400,
      statusMessage: "startedAt is in the future.",
    });
  if (now.getTime() - startedAt.getTime() > MAX_RECORD_AGE_MS)
    throw createError({
      statusCode: 400,
      statusMessage: "Session is too old to record.",
    });

  const existing = await prisma.playSession.findUnique({
    where: { id: body.sessionId },
    select: { userId: true, durationSeconds: true },
  });
  if (existing) {
    if (existing.userId !== user.id)
      throw createError({ statusCode: 404, statusMessage: "Not found." });
    return { durationSeconds: existing.durationSeconds ?? 0, duplicate: true };
  }

  const game = await prisma.game.findUnique({
    where: { id: body.gameId },
    select: { id: true },
  });
  if (!game)
    throw createError({ statusCode: 404, statusMessage: "Game not found." });

  const durationSeconds = clampSessionDuration(
    body.clientDurationSecs,
    startedAt,
    now,
  );
  const endedAt = new Date(startedAt.getTime() + durationSeconds * 1000);

  const candidates = await prisma.playSession.findMany({
    where: {
      userId: user.id,
      startedAt: { lt: endedAt },
      OR: [{ endedAt: null }, { endedAt: { gt: startedAt } }],
    },
    select: {
      id: true,
      gameId: true,
      startedAt: true,
      endedAt: true,
      lastHeartbeatAt: true,
    },
  });
  // Open sessions of this game that started inside the span and never
  // heartbeated: this very play, whose start (or several retried starts)
  // reached the server too late for the client to use. No client will ever
  // stop them, so they are closed at zero length and the record stands for
  // the play instead.
  const adopted = candidates.filter(
    (o) =>
      o.endedAt === null &&
      o.lastHeartbeatAt === null &&
      o.gameId === body.gameId &&
      o.startedAt.getTime() >= startedAt.getTime() - MAX_FUTURE_SKEW_MS,
  );
  const adoptedIds = new Set(adopted.map((o) => o.id));
  // Everything else is time this user is known to have spent elsewhere. An
  // open session counts only up to its last heartbeat, with no grace: only
  // time that certainly happened may push the record aside.
  const busy = candidates
    .filter((o) => !adoptedIds.has(o.id))
    .map((o) => ({
      start: o.startedAt.getTime(),
      end: (o.endedAt ?? o.lastHeartbeatAt ?? o.startedAt).getTime(),
    }));

  // The record keeps every second that overlaps nothing, in as many pieces
  // as it takes, then the 24-hours-per-day cap trims from the end.
  const credited = await secondsCreditedInDayBefore(user.id, endedAt);
  const pieces = capSpans(
    freeSpans(startedAt.getTime(), endedAt.getTime(), busy),
    Math.max(MAX_SECONDS_PER_DAY - credited, 0),
  );
  const total = pieces.reduce(
    (sum, p) => sum + Math.floor((p.end - p.start) / 1000),
    0,
  );
  if (total <= 0 && durationSeconds > 0) {
    if (credited >= MAX_SECONDS_PER_DAY)
      throw createError({
        statusCode: 409,
        statusMessage: "No playtime left to credit for that day.",
      });
    // Not one of the client's final answers: the sessions in the way may
    // still be corrected by a queued stop, so the record is tried again.
    throw createError({
      statusCode: 409,
      statusMessage: "Session is covered by other play.",
    });
  }

  // The first piece carries the client's id, so a replay finds it and
  // changes nothing; any further pieces get ids derived from it.
  const rows = (
    pieces.length > 0
      ? pieces
      : [{ start: startedAt.getTime(), end: startedAt.getTime() }]
  ).map((p, i) => ({
    id: i === 0 ? body.sessionId : `${body.sessionId}-${i}`,
    gameId: body.gameId,
    userId: user.id,
    startedAt: new Date(p.start),
    endedAt: new Date(p.end),
    durationSeconds: Math.floor((p.end - p.start) / 1000),
  }));
  try {
    await prisma.$transaction([
      ...adopted.map((o) =>
        prisma.playSession.updateMany({
          where: { id: o.id, userId: user.id, endedAt: null },
          data: { endedAt: o.startedAt, durationSeconds: 0 },
        }),
      ),
      prisma.playSession.createMany({ data: rows }),
    ]);
  } catch (e) {
    // Two replays of the same record racing each other: the other one made
    // the rows, which is the outcome both wanted.
    if ((e as { code?: string })?.code === "P2002")
      return { durationSeconds: total, duplicate: true };
    throw e;
  }

  await recomputeUserGamePlaytime(body.gameId, user.id);

  return {
    durationSeconds: total,
    duplicate: false,
    adopted: adopted.length,
  };
});
